data:
  min_year: 1990
  max_year: 2024
  avg_fire_count: "1,131"
  avg_burn_ha: "2,584,733"
  avg_burn_km: "25,847 km²"
  total_fire_count: "39,924"
  total_burn_ha: "90,465,666"
  total_burn_km: "9,046,56 km²"

